name: Do Task Worker

on:
  workflow_dispatch:
    inputs:
      workers:
        description: "Worker array, e.g. [1,2,3,4,5]"
        required: false
        default: "[1,2,3,4,5,6,7,8,9,10]"
      task_id:
        description: "The ID of the scan task in the database"
        required: true

jobs:
  worker:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        worker_id: ${{ fromJson(github.event.inputs.workers) }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Init Go Modules
        run: go mod tidy && go mod download

      - name: Run Worker
        env:
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          REDIS_PASS: ${{ secrets.REDIS_PASS }}
        run: |
          go run main.go --worker=${{ matrix.worker_id }} --task=${{ github.event.inputs.task_id }}